# permissions for end users to view nonrtmonitorings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: non-rt-controller
    app.kubernetes.io/managed-by: kustomize
  name: nonrtmonitoring-viewer-role
rules:
- apiGroups:
  - sdv.non-rt
  resources:
  - nonrtmonitorings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sdv.non-rt
  resources:
  - nonrtmonitorings/status
  verbs:
  - get
