---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - sdv.non-rt
  resources:
  - nonrtmonitorings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sdv.non-rt
  resources:
  - nonrtmonitorings/finalizers
  verbs:
  - update
- apiGroups:
  - sdv.non-rt
  resources:
  - nonrtmonitorings/status
  verbs:
  - get
  - patch
  - update
